version: '3'

services:
  mongo:
    image: mongo:latest
    env_file: ../env/mongo.env
    ports:
      - 27017:27017
    volumes:
      - ./init_mongo.js:/docker-entrypoint-initdb.d/init_mongo.js:ro
    command: [--auth]